<% ENV['TEST_ENV_NUMBER'] ||= '' %>

<%= "#{::Rails.env}: &#{::Rails.env}"%>
  adapter: mysql2
  encoding: utf8
  database: <%= ::Rails.env=='test' ? ::Rails.env + ENV['TEST_ENV_NUMBER'] : ::Rails.env%>
  username: <%= Afterburner.SHARDS_CONFIG['db']['master']['username'] ? Afterburner.SHARDS_CONFIG['db']['master']['username'] : 'root'%>
  password: <%=  Afterburner.SHARDS_CONFIG['db']['master']['password'] if  Afterburner.SHARDS_CONFIG['db']['master']['password'] %>
  host: <%= Afterburner.SHARDS_CONFIG['db']['master']['ip']%>
  port: <%= Afterburner.SHARDS_CONFIG['db']['master']['port'] || 3306 %>
  pool: 24

